version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 084828581506.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}-${CODEBUILD_BUILD_NUMBER}
      - docker build -t shyamdev-dev-image-gallery:$IMAGE_TAG .
      - docker tag shyamdev-dev-image-gallery:$IMAGE_TAG 084828581506.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/shyamdev-dev-image-gallery:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 084828581506.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/shyamdev-dev-image-gallery:$IMAGE_TAG
      - printf '[{"name":"image-gallery","imageUri":"084828581506.dkr.ecr.%s.amazonaws.com/shyamdev-dev-image-gallery:%s"}]' "$AWS_DEFAULT_REGION" "$IMAGE_TAG" > imagedefinitions.json
      - echo Build completed

artifacts:
  files:
    - imagedefinitions.json
